# Site settings
title: Shubham Singhal
description: Portfolio
baseurl: "/"
url: "https://cseshubhamsinghal.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shubham Singhal
user_description: Machine Learning Enthusiast
user_title: Computer Science Engineer
email: cse.shubhamsinghal@gmail.com
twitter_username: lorem_ipsum
github_username:  cseshubhamsinghal
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-merlot
